from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
options=webdriver.ChromeOptions()
options.add_experimental_option("detach",True)
options.add_argument("--disable-notification")
driver=webdriver.Chrome(options=options)
driver.maximize_window()
driver.get("https://demo.automationtesting.in/Frames.html")
sleep(2)
driver.find_element(By.LINK_TEXT,"Iframe with in an Iframe").click()
iframe=driver.find_element(By.XPATH,"//div[@id='Multiple']/iframe")
driver.switch_to.frame(iframe)
sleep(2)
nested_iframe=driver.find_element(By.XPATH,"//div[@class='iframe-container']/iframe")
driver.switch_to.frame(nested_iframe)
sleep(2)
driver.find_element(By.XPATH,"//input[@type='text']").send_keys("Vaishnavi")
sleep(2)
driver.switch_to.default_content()
driver.find_element(By.LINK_TEXT,"Home").click()
